spring.datasource.url=jdbc:postgresql://dpg-d203gqi4d50c73b95icg-a.oregon-postgres.render.com:5432/banco_sgrapp
spring.datasource.username=banco_sgrapp_user
spring.datasource.password=J8naQwQYDlFS2zaWmcU5KEzxdTnAZxtg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
